### ISSUE TITLE
Wrong column number in 0.4.3

### ISSUE THREAD

**Issue by iamvdo** [mozilla/source-map#192]
As #191, I also get errors with 0.4.3 from PostCSS sourcemap.

It returns wrong column from `generatedPositionFor`.

I have this file `module.css`:
```css
.module {
  color: #fff
}
```
And the processed file:
```css
.import{color:#fff}.module{color:#fff}.main{color:#fff}
```

When I use :
```javascript
var smc = new SourceMap.SourceMapConsumer(PostCSS_map);
var positions = smc.generatedPositionFor({source: 'module.css', line: 1, column: 0});
```
`positions.column == 19` with @0.4.2 and `positions.column == 27` with @0.4.3

Is it intended? Am I missing something?
