### ISSUE TITLE
throw new Error('Invalid mapping: ' + JSON.stringify({

### ISSUE THREAD

**Issue by rossjcooper** [mozilla/source-map#301]
Getting this exception thrown now and again, the scss looks ok. 

```
/project/node_modules/clean-css/node_modules/source-map/lib/source-map-generator.js:289
      throw new Error('Invalid mapping: ' + JSON.stringify({
      ^

Error: Invalid mapping: {"generated":{"line":1,"column":8309},"source":"custom.scss","original":{"line":342,"column":-1},"name":null}
    at SourceMapGenerator_validateMapping [as _validateMapping] (/project/node_modules/clean-css/node_modules/source-map/lib/source-map-generator.js:289:13)
    at SourceMapGenerator_addMapping [as addMapping] (/project/node_modules/clean-css/node_modules/source-map/lib/source-map-generator.js:101:12)
    at trackMapping (/project/node_modules/clean-css/lib/writer/source-maps.js:59:30)
    at trackAllMappings (/project/node_modules/clean-css/lib/writer/source-maps.js:44:5)
    at track (/project/node_modules/clean-css/lib/writer/source-maps.js:35:5)
    at store (/project/node_modules/clean-css/lib/writer/source-maps.js:20:3)
    at rules (/project/node_modules/clean-css/lib/writer/helpers.js:50:5)
    at all (/project/node_modules/clean-css/lib/writer/helpers.js:210:9)
    at serializeStylesAndSourceMap (/project/node_modules/clean-css/lib/writer/source-maps.js:94:3)
    at /project/node_modules/clean-css/lib/clean.js:105:29
```

**Comment by cspotcode** [comment]
The original column is -1, so that's wrong.  Can you post a minimal reproduction?  I've been debugging a similar issue but won't be able to track yours down without any code.  This could be a problem with scss, for example.

**Comment by rossjcooper** [comment]
This is the chunk of scss it appears to be complaining about, line 342 is the `&:hover`. I have other `&` selectors in use that don't seem to cause an issue in code above this, and if I remove the `& :hover` from the code below it compiles fine.

```
button, input[type="button"], input[type="submit"], input[type="reset"] {
  transition: all ease .2s;
  &:hover{
    background-color: #28A956;
  }
}
```

**Comment by aifrim** [comment]
What is with this negative column problem?
`bootstrap-sass` has it in several places. Here is one: `bootstrap/mixins/_buttons.scss:9`

```scss
@mixin button-variant($color, $background, $border) {
    color: $color;
    background-color: $background;
    border-color: $border;
    &:focus, // here is the problem
    &.focus {
        color: $color;
        background-color: darken($background, 10%);
        border-color: darken($border, 25%);
    }
    &:hover {
        color: $color;
        background-color: darken($background, 10%);
        border-color: darken($border, 12%);
    }
    &:active,
    &.active,
    .open>&.dropdown-toggle {
        color: $color;
        background-color: darken($background, 10%);
        border-color: darken($border, 12%);
        &:hover,
        &:focus,
        &.focus {
            color: $color;
            background-color: darken($background, 17%);
            border-color: darken($border, 25%);
        }
    }
    &:active,
    &.active,
    .open>&.dropdown-toggle {
        background-image: none;
    }
    &.disabled,
    &[disabled],
    fieldset[disabled] & {
        &:hover,
        &:focus,
        &.focus {
            background-color: $background;
            border-color: $border;
        }
    }
    .badge {
        color: $background;
        background-color: $color;
    }
}

// Button sizes
@mixin button-size($padding-vertical, $padding-horizontal, $font-size, $line-height, $border-radius) {
    padding: $padding-vertical $padding-horizontal;
    font-size: $font-size;
    line-height: $line-height;
    border-radius: $border-radius;
}
```
same with `bootstrap/mixins/_clearfix.scss:14`

```scss
@mixin clearfix() {
    &:before,
    &:after { // here is the problem
        content: " "; // 1
        display: table; // 2
    }
    &:after {
        clear: both;
    }
}
```

And the list goes on. I managed to bypass the error in `_clearfix.scss` by indenting the file to my `.editorconfig` settings.

Apparently the `aOriginal.column` is negative for some reason in `source-map-generator.js:283`.
